# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: gitload 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "gitload"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Simon Oulevay (Alpha Hydrae)"]
  s.date = "2016-11-28"
  s.description = "Gitload provides a DSL to easily clone all your repositories from GitHub and other providers."
  s.email = "git@alphahydrae.com"
  s.executables = ["gitload"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "bin/gitload",
    "lib/gitload.rb",
    "lib/gitload/commands.rb",
    "lib/gitload/commands/load.rb",
    "lib/program.rb"
  ]
  s.homepage = "https://github.com/AlphaHydrae/gitload"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.1"
  s.summary = "Gitload downloads your repositories."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paint>, ["~> 1.0"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.2"])
      s.add_runtime_dependency(%q<octokit>, ["~> 4.6"])
      s.add_development_dependency(%q<rake>, ["~> 11.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<rspec-its>, ["~> 1.1"])
      s.add_development_dependency(%q<fakefs>, ["~> 0.9.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.12.0"])
    else
      s.add_dependency(%q<paint>, ["~> 1.0"])
      s.add_dependency(%q<commander>, ["~> 4.2"])
      s.add_dependency(%q<octokit>, ["~> 4.6"])
      s.add_dependency(%q<rake>, ["~> 11.0"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<rspec-its>, ["~> 1.1"])
      s.add_dependency(%q<fakefs>, ["~> 0.9.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rake-version>, ["~> 1.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.12.0"])
    end
  else
    s.add_dependency(%q<paint>, ["~> 1.0"])
    s.add_dependency(%q<commander>, ["~> 4.2"])
    s.add_dependency(%q<octokit>, ["~> 4.6"])
    s.add_dependency(%q<rake>, ["~> 11.0"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<rspec-its>, ["~> 1.1"])
    s.add_dependency(%q<fakefs>, ["~> 0.9.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rake-version>, ["~> 1.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.12.0"])
  end
end

